// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// IMPORTANT: Pour les migrations, utiliser POSTGRES_URL_NON_POOLING (connexion directe)
// Les migrations nécessitent une connexion directe, pas de pooling
// POSTGRES_PRISMA_URL est pour le runtime (avec pooling)
const DIRECT_URL = process.env.POSTGRES_URL_NON_POOLING || process.env.DATABASE_URL || process.env.POSTGRES_URL || "postgresql://placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DIRECT_URL,
  },
});
