// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// IMPORTANT: Pour les migrations, utiliser une connexion directe (pas de pooling, pas d'Accelerate)
// Les migrations nécessitent une connexion directe à PostgreSQL
// Pour Prisma Accelerate: utiliser DATABASE_URL ou POSTGRES_URL (URL directe)
// Pour Vercel Postgres: utiliser POSTGRES_URL_NON_POOLING (URL directe)
const DIRECT_URL = process.env.POSTGRES_URL_NON_POOLING || process.env.DATABASE_URL || process.env.POSTGRES_URL || "postgresql://placeholder@localhost:5432/placeholder";
const POOLING_URL = process.env.POSTGRES_PRISMA_URL || DIRECT_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DIRECT_URL,  // Pour les migrations (connexion directe requise)
  },
  // Note: POSTGRES_PRISMA_URL sera utilisé dans lib/db.ts pour le runtime PrismaClient
});
